server.port=${PORT:8085}

eureka.client.enabled=true
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=${HOSTNAME:localhost}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka}

spring.application.name=gateway-filters

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

spring.cloud.gateway.default-filters[0]=DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-origins=${ALLOWED_ORIGINS:*}
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-headers=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-methods[0]=POST

management.endpoint.gateway.enabled=${ROUTE_TABLES_ENABLED:true}
management.endpoints.web.exposure.include=*

logging.file.name=target/log/gateway-filters.log
logging.level.root=INFO

auth.server.jwks-uri=${AUTH_SERVER_JWKS_URI:http://localhost:8084/api-oauth2/.well-known/jwks.json}

gateway.security.whitelist=/api-oauth2/**,/*/api-oauth2/**,/.well-known/**,/*/.well-known/**,/actuator/health
logging.level.org.springframework.security=DEBUG
logging.level.com.relatos_papel.gateway_filters=DEBUG

# Redis
spring.redis.host=${REDIS_HOST:localhost}
spring.redis.port=${REDIS_PORT:6379}

spring.redis.timeout=2000ms
spring.redis.database=${REDIS_DATABASE:0}

# === RATE LIMITER CONFIG ===
custom.rate-limiter.replenish-rate=2
custom.rate-limiter.burst-capacity=3
custom.rate-limiter.enabled=true

spring.cloud.gateway.routes[0].id=oauth2
spring.cloud.gateway.routes[0].uri=lb://oauth2-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/*/api-oauth2/**
spring.cloud.gateway.routes[0].filters[0]=RewritePath=/[^/]+(?<segment>/api-oauth2/.*), ${segment}
spring.cloud.gateway.routes[0].filters[1]=RequestRateLimiter=redisRateLimiter, customKeyResolver

